### ISSUE TITLE
GH액션 실행/로컬실행 시 헤더 관련 문제 발생 (14.x, 15.x)

### ISSUE THREAD

**Issue by start2018** [eduro-hcs/jaga_jindan_automatic_js#2]
`Run npm start

> jaga_jindan_js@1.0.0 start /home/runner/work/hcs/hcs
> node index.js

(node:2297) UnhandledPromiseRejectionWarning: TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Authorization"
    at ClientRequest.setHeader (_http_outgoing.js:561:3)
    at new ClientRequest (_http_client.js:251:14)
    at Object.request (https.js:313:10)
    at RedirectableRequest._performRequest (/home/runner/work/hcs/hcs/node_modules/follow-redirects/index.js:241:24)
    at new RedirectableRequest (/home/runner/work/hcs/hcs/node_modules/follow-redirects/index.js:60:8)
    at Object.wrappedProtocol.request (/home/runner/work/hcs/hcs/node_modules/follow-redirects/index.js:437:14)
    at dispatchHttpRequest (/home/runner/work/hcs/hcs/node_modules/axios/lib/adapters/http.js:179:25)
    at new Promise (<anonymous>)
    at httpAdapter (/home/runner/work/hcs/hcs/node_modules/axios/lib/adapters/http.js:21:10)
    at dispatchRequest (/home/runner/work/hcs/hcs/node_modules/axios/lib/core/dispatchRequest.js:52:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2297) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:2297) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by nnnlog** [comment]
로컬에서 실행하였을 때는 정상 작동하나요?

**Comment by start2018** [comment]
아, Node 14.x가 문제였네요. Node 15.x로 하면 됩니다.

**Comment by start2018** [comment]
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Authorization"
    at ClientRequest.setHeader (node:_http_outgoing:576:3)
    at new ClientRequest (node:_http_client:266:14)
    at Object.request (node:https:333:10)
    at RedirectableRequest._performRequest (/home/runner/work/hcs/hcs/node_modules/follow-redirects/index.js:241:24)
    at new RedirectableRequest (/home/runner/work/hcs/hcs/node_modules/follow-redirects/index.js:60:8)
    at Object.wrappedProtocol.request (/home/runner/work/hcs/hcs/node_modules/follow-redirects/index.js:437:14)
    at dispatchHttpRequest (/home/runner/work/hcs/hcs/node_modules/axios/lib/adapters/http.js:179:25)
    at new Promise (<anonymous>)
    at httpAdapter (/home/runner/work/hcs/hcs/node_modules/axios/lib/adapters/http.js:21:10)
    at dispatchRequest (/home/runner/work/hcs/hcs/node_modules/axios/lib/core/dispatchRequest.js:52:10) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}


Node 15.x로 실행시 이 오류가 뜹니다. 로컬로 실행시 에도 문제가 있습니다. (새벽 6시 자가진단 시)

**Comment by start2018** [comment]
EduCode를 sen으로 적용하니 잘됬습니다. 계속 이슈 걸어서 죄송합니다.
